// Generated by https://pagedraw.io/pages/9895
import React from 'react';
import './buttongroup.css';

function render() {
    return <div className="pd-onhover-parent buttongroup">
        { (this.props.state === "default") ?
            <div className="buttongroup-default-3">
                <div className="buttongroup-0-0-0">
                    <div className="buttongroup-0-0-0-0" /> 
                    <div onClick={this.props.onClick} className="buttongroup-rectangle-3" style={{"background": this.props.button}}>
                        <div className="buttongroup-0-0-0-1-0">
                            <div className="buttongroup-0-0-0-1-0-0" /> 
                            <div className="buttongroup-kay_t_ol-4">
                                { this.props.btext }
                            </div>
                            <div className="buttongroup-0-0-0-1-0-2" /> 
                        </div>
                    </div>
                    <div className="buttongroup-0-0-0-2" /> 
                </div>
            </div>
        : null}
        <div className="pd-onhover buttongroup-_hover-5">
            <div className="buttongroup-1-0">
                <div className="buttongroup-1-0-0" /> 
                <div onClick={this.props.onClick} className="buttongroup-rectangle-0" style={{"background": this.props.button}}>
                    <div className="buttongroup-1-0-1-0">
                        <div className="buttongroup-1-0-1-0-0" /> 
                        <div className="buttongroup-kay_t_ol-0">
                            { this.props.btext }
                        </div>
                        <div className="buttongroup-1-0-1-0-2" /> 
                    </div>
                </div>
                <div className="buttongroup-1-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}