// Generated by https://pagedraw.io/pages/9923
import React from 'react';
import './class.css';

function render() {
    return <div className="pd-onhover-parent class">
        <div className="pd-onhover class-_hover-6">
            <div className="class-0-0">
                <div className="class-0-0-0" /> 
                <div onClick={()=>this.props.history.push("/dersler/"+this.props.elem)} className="class-rectangle-3">
                    <div className="class-0-0-1-0">
                        <div className="class-ders_ismi-2">
                            { this.props.elem }
                        </div>
                        <div className="class-0-0-1-0-1">
                            <div className="class-0-0-1-0-1-0">
                                <div className="class-image-2" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="class-0-0-2" /> 
            </div>
        </div>
        { (this.props.state === "default") ?
            <div className="class-default-9">
                <div className="class-1-0-0">
                    <div className="class-1-0-0-0" /> 
                    <div onClick={()=>this.props.history.push("/dersler/"+this.props.elem)} className="class-rectangle-0">
                        <div className="class-1-0-0-1-0">
                            <div className="class-ders_ismi-0">
                                { this.props.elem }
                            </div>
                            <div className="class-1-0-0-1-0-1">
                                <div className="class-1-0-0-1-0-1-0">
                                    <div className="class-image-8" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="class-1-0-0-2" /> 
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}