// Generated by https://pagedraw.io/pages/9839
import React from 'react';
import './default.css';

function render() {
    return <div className="default-default-3">
        <div className="default-0">
            <div className="default-rectangle-1" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}