// Generated by https://pagedraw.io/pages/9895
import Buttongroup from './buttongroup';
import React from 'react';
import './homepage.css';

function render() {
    return <div className="homepage-homepage-0">
        <div className="homepage-0">
            <div className="homepage-0-0" /> 
            <div className="homepage-image-5" /> 
            <div className="homepage-0-2" /> 
        </div>
        <div className="homepage-1">
            <div className="homepage-1-0" /> 
            <div className="homepage-konular_renin_hat_rl_ile_asla_unutmay_n_-0">
                <div>{"Konuları öğrenin."}</div>
                <div>{"Hatırlı ile asla unutmayın."}</div>
            </div>
            <div className="homepage-1-2" /> 
        </div>
        <div className="homepage-2">
            <div className="homepage-2-0" /> 
            <div className="homepage-kayit-7">
                <Buttongroup state={"default"} button={"rgb(146, 228, 255)"} btext={"Kayıt ol"} onClick={(()=>this.props.history.push('/kayit'))} /> 
            </div>
            <div className="homepage-2-2" /> 
        </div>
        <div className="homepage-3">
            <div className="homepage-3-0" /> 
            <div className="homepage-giris-1">
                <Buttongroup state={"default"} button={"rgb(146, 255, 150)"} btext={"Giriş yap"} onClick={(()=>this.props.history.push('/giris'))} /> 
            </div>
            <div className="homepage-3-2" /> 
        </div>
        <div className="homepage-4">
            <div className="homepage-4-0" /> 
            <div className="homepage-aral_kl_tekrarlama_sistemi_srs_ile_rendikleriniz_akl_n_zda_kals_n_-0">
                {"Aralıklı Tekrarlama Sistemi(SRS) ile öğrendikleriniz aklınızda kalsın."}
            </div>
            <div className="homepage-4-2" /> 
        </div>
        <div className="homepage-5">
            <div className="homepage-5-0" /> 
            <div className="homepage-hat_rl_leitner_sistemini_kullan_r_bilgileri_tam_unutmak_zereyken_size_hat_rlat_r_ve_uzun_s_reli_haf_zan_za_girmesini_sa_lar-0">
                {"Hatırlı, Leitner sistemini kullanır. Bilgileri tam unutmak üzereyken size hatırlatır ve uzun süreli hafızanıza girmesini sağlar"}
            </div>
            <div className="homepage-5-2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}