// Generated by https://pagedraw.io/pages/9893
import {Link} from 'react-router-dom';
import firebase from '../firebase.js';
import React from 'react';
import './login_multistate.css';

function render() {
    return <div className="login_multistate">
        { (this.props.state === "loggedin") ?
            <div className="login_multistate-loggedin-1">
                <div className="login_multistate-0-0-0">
                    <div onClick={()=>firebase.auth().signOut()} className="login_multistate-giri_yap-4">
                        {"Çıkış Yap"}
                    </div>
                </div>
                <div className="login_multistate-0-0-1">
                    <div className="login_multistate-0-0-1-0" /> 
                    <div className="login_multistate-text-3">
                        { this.props.username }
                    </div>
                    <div className="login_multistate-0-0-1-2" /> 
                </div>
            </div>
        : null}
        { (this.props.state === "default") ?
            <div className="login_multistate-default-8">
                <div className="login_multistate-1-0-0">
                    <div className="login_multistate-giri_yap-0">
                        <Link to="/giris">Giriş Yap</Link>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}