// Generated by https://pagedraw.io/pages/9897
import React from 'react';
import './login.css';

function render() {
    return <div className="login-login-0">
        <div className="login-0">
            <div className="login-giri_yap_n-0">{"Giriş Yapın"}</div>
        </div>
        <div className="login-1">
            <div className="login-1-0" /> 
            <div className="login-rectangle_6">
                <div className="login-1-1-0">
                    <div className="login-rectangle_3">
                        <div className="login-1-1-0-0-0">
                            <div className="login-1-1-0-0-0-0">
                                <div className="login-1-1-0-0-0-0-0">
                                    <div className="login-email_-0">{"Email:"}</div>
                                </div>
                            </div>
                            <div className="login-1-1-0-0-0-1">
                                <div className="login-1-1-0-0-0-1-0">
                                    <div className="login-rectangle_2">
                                        <div className="login-1-1-0-0-0-1-0-0-0">
                                            <input type="text" placeholder="Email" value={this.props.email} onChange={this.props.onEC} className="login-text_input-0" /> 
                                        </div>
                                        <div className="login-1-1-0-0-0-1-0-0-1">
                                            <div className="login-line-4" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="login-1-1-1">
                    <div className="login-rectangle_5">
                        <div className="login-1-1-1-0-0">
                            <div className="login-1-1-1-0-0-0">
                                <div className="login-1-1-1-0-0-0-0">
                                    <div className="login-_ifre_-0">{"Şifre:"}</div>
                                </div>
                            </div>
                            <div className="login-1-1-1-0-0-1">
                                <div className="login-1-1-1-0-0-1-0">
                                    <div className="login-rectangle_4">
                                        <div className="login-1-1-1-0-0-1-0-0-0">
                                            <input type="password" placeholder="Şifre" value={this.props.pass} onChange={this.props.onPC} className="login-text_input-00" /> 
                                        </div>
                                        <div className="login-1-1-1-0-0-1-0-0-1">
                                            <div className="login-line-0" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="login-1-1-2">
                    <div onClick={()=>this.props.history.push('/kayit')} className="login-kay_t_olun-0">
                        {"Kayıt olun"}
                    </div>
                    <div className="login-1-1-2-1" /> 
                </div>
                <div className="login-1-1-3">
                    <div onClick={()=>this.props.history.push('/sifremiunuttum')} className="login-_ifremi_unuttum-0">
                        {"Şifremi unuttum"}
                    </div>
                </div>
            </div>
            <div className="login-1-2" /> 
        </div>
        <div className="login-2">
            <div onClick={this.props.login} className="login-rectangle-0">
                <div className="login-2-0-0">
                    <div className="login-giri_yap-0">{"Giriş Yap"}</div>
                </div>
            </div>
        </div>
        <div className="login-3" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}