// Generated by https://pagedraw.io/pages/9870
import React from 'react';
import './multibutton.css';

function render() {
    return <div className="multibutton">
        { (this.props.state === "default") ?
            <div className="multibutton-default-2">
                <div className="multibutton-0-0-0">
                    <div className="multibutton-rectangle_2">
                        <div className="multibutton-0-0-0-0-0">
                            <div className="multibutton-0-0-0-0-0-0" /> 
                            <div className="multibutton-do_ru-9">
                                { this.props.text }
                            </div>
                            <div className="multibutton-0-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="multibutton-0-0-1" /> 
            </div>
        : null}
        { (this.props.state === "correct") ?
            <div className="multibutton-correct-3">
                <div className="multibutton-1-0-0">
                    <div className="multibutton-rectangle_2-6">
                        <div className="multibutton-1-0-0-0-0">
                            <div className="multibutton-1-0-0-0-0-0" /> 
                            <div className="multibutton-do_ru-5">
                                { this.props.text }
                            </div>
                            <div className="multibutton-1-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="multibutton-1-0-1" /> 
            </div>
        : null}
        { (this.props.state === "wrong") ?
            <div className="multibutton-wrong-5">
                <div className="multibutton-2-0-0">
                    <div className="multibutton-rectangle_2-5">
                        <div className="multibutton-2-0-0-0-0">
                            <div className="multibutton-2-0-0-0-0-0" /> 
                            <div className="multibutton-do_ru-0">
                                { this.props.text }
                            </div>
                            <div className="multibutton-2-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="multibutton-2-0-1" /> 
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}