// Generated by https://pagedraw.io/pages/9870
import BlankedQuestion from '../../BlankedQuestion.jsx';
import Multistate_group_2 from './multistate_group_2';
import React from 'react';
import './multistate_group.css';

function render() {
    return <div className="multistate_group">
        { (this.props.state === "fill") ?
            <div className="multistate_group-fill-7">
                <div className="multistate_group-0-0-0">
                    <div className="multistate_group-0-0-0-0" /> 
                    <div className="multistate_group-rectangle-1">
                        <div className="multistate_group-0-0-0-1-0">
                            <div className="multistate_group-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_aenean_lacinia_mauris_ac_orci_ultrices_efficitur_aliquam_ipsum_neque_convallis_et_venenatis_aliquet_tempus_eget-5">
                                <BlankedQuestion question={this.props.question} onChange={this.props.onChange} answer={this.props.answer} currentText={this.props.currentText} submitanswer={this.props.submitanswer}/>
                            </div>
                        </div>
                    </div>
                    <div className="multistate_group-0-0-0-2" /> 
                </div>
            </div>
        : null}
        { (this.props.state === "tf") ?
            <div className="multistate_group-tf-7">
                <div className="multistate_group-1-0-0">
                    <div className="multistate_group-1-0-0-0" /> 
                    <div className="multistate_group-rectangle-0">
                        <div className="multistate_group-1-0-0-1-0">
                            <div className="multistate_group-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_aenean_lacinia_mauris_ac_orci_ultrices_efficitur_aliquam_ipsum_neque_convallis_et_venenatis_aliquet_tempus_eget-0">
                                { this.props.question }
                            </div>
                        </div>
                        <div className="multistate_group-1-0-0-1-1">
                            <div className="multistate_group-multistate_group_2">
                                <Multistate_group_2 state={(this.props.answer==true ? "correct" : this.props.answer==false ? "wrong" : "default")} text={"DOĞRU"} /> 
                            </div>
                            <div className="multistate_group-multistate_group_2_">
                                <Multistate_group_2 state={(this.props.answer==false ? "correct" : this.props.answer==true ? "wrong" : "default")} text={"YANLIŞ"} /> 
                            </div>
                        </div>
                    </div>
                    <div className="multistate_group-1-0-0-2" /> 
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}