// Generated by https://pagedraw.io/pages/9893
import {Link} from 'react-router-dom'
import Login_multistate from './login_multistate';
import React from 'react';
import './navbar.css';

function render() {
    return <div className="navbar-navbar-0">
        <div className="navbar-0">
            <div className="navbar-0-0" /> 
            <div className="navbar-0-1">
                <div className="navbar-0-1-0">
                    <div className="navbar-_al_ma-0">
                        <Link to="/calisma">Çalışma</Link>
                    </div>
                </div>
            </div>
            <div className="navbar-0-2" /> 
            <div className="navbar-0-3">
                <div className="navbar-0-3-0">
                    <div className="navbar-s_n_f-0">
                        <Link to="/sinif">Sınıf</Link>
                    </div>
                </div>
            </div>
            <div className="navbar-0-4" /> 
            <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/8564/acc3/e50b60da861f301256b50e200746ae72" onClick={()=>this.props.history.push('/')} className="navbar-image-6" /> 
            <div className="navbar-0-6" /> 
            <div className="navbar-0-7">
                <div className="navbar-0-7-0">
                    <div className="navbar-dersler-0">
                        <Link to="/dersler">Dersler</Link>
                    </div>
                </div>
            </div>
            <div className="navbar-0-8" /> 
            <div className="navbar-0-9">
                <div className="navbar-0-9-0">
                    <div className="navbar-login-6">
                        <Login_multistate state={(this.props.username ? "loggedin" : "default")} username={this.props.username} /> 
                    </div>
                </div>
            </div>
            <div className="navbar-0-10" /> 
        </div>
        <div className="navbar-1">
            <div className="navbar-line-1" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}