// Generated by https://pagedraw.io/pages/9870
import BlankedQuestion from '../../BlankedQuestion.jsx';
import Multistate_group from './multistate_group';
import React from 'react';
import './questioncomponent.css';

function render() {
    return <div className="questioncomponent-questioncomponent-0">
        <div className="questioncomponent-0" /> 
        <div className="questioncomponent-1">
            <div className="questioncomponent-1-0" /> 
            <div className="questioncomponent-multistate_group_instance-7">
                <Multistate_group state={this.props.type} answer={this.props.answer} question={this.props.question} onChange={this.props.onChange} currentText={this.props.currentText} submitanswer={this.props.submitanswer} /> 
            </div>
            <div className="questioncomponent-1-2" /> 
        </div>
        <div className="questioncomponent-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}