// Generated by https://pagedraw.io/pages/9923
import Section from './section';
import React from 'react';
import './sections.css';

function render() {
    return <div className="sections-sections-4">
        <div className="sections-0">
            <div className="sections-0-0" /> 
            <div className="sections-0-1">
                { this.props.list.map((elem, i) => {
                    return <div key={i} className="sections-rectangle_2">
                        <div className="sections-0-1-0-0-0">
                            <div className="sections-0-1-0-0-0-0" /> 
                            <div className="sections-section-4">
                                <Section state={"default"} elem={elem} addSection={this.props.addSection} /> 
                            </div>
                            <div className="sections-0-1-0-0-0-2" /> 
                        </div>
                    </div>;
                }) }
            </div>
            <div className="sections-0-2" /> 
        </div>
        <div className="sections-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}