// Generated by https://pagedraw.io/pages/9923
import React from 'react';
import './section.css';

function render() {
    return <div className="pd-onhover-parent section">
        { (this.props.state === "default") ?
            <div className="section-default-0">
                <div className="section-0-0-0">
                    <div className="section-0-0-0-0" /> 
                    <div onClick={this.props.addSection.bind(null,this.props.elem)} className="section-rectangle-9">
                        <div className="section-0-0-0-1-0">
                            <div className="section-ders_ismi-6">
                                { this.props.elem }
                            </div>
                            <div className="section-image-3" /> 
                        </div>
                    </div>
                    <div className="section-0-0-0-2" /> 
                </div>
            </div>
        : null}
        <div className="pd-onhover section-_hover-7">
            <div className="section-1-0">
                <div className="section-1-0-0" /> 
                <div onClick={this.props.addSection.bind(null,this.props.elem)} className="section-rectangle-4">
                    <div className="section-1-0-1-0">
                        <div className="section-ders_ismi-5">
                            { this.props.elem }
                        </div>
                        <div className="section-image-5" /> 
                    </div>
                </div>
                <div className="section-1-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}