// Generated by https://pagedraw.io/pages/9898
import React from 'react';
import './signup.css';

function render() {
    return <div className="signup-signup-0">
        <div className="signup-0">
            <div className="signup-0-0" /> 
            <div className="signup-kay_t_olun-0">{"Kayıt olun"}</div>
            <div className="signup-0-2" /> 
        </div>
        <div className="signup-1">
            <div className="signup-1-0" /> 
            <div className="signup-rectangle_6">
                <div className="signup-1-1-0">
                    <div className="signup-rectangle_3">
                        <div className="signup-1-1-0-0-0">
                            <div className="signup-1-1-0-0-0-0">
                                <div className="signup-1-1-0-0-0-0-0">
                                    <div className="signup-email_-4">{"Kullanıcı adı:"}</div>
                                </div>
                            </div>
                            <div className="signup-1-1-0-0-0-1">
                                <div className="signup-1-1-0-0-0-1-0">
                                    <div className="signup-rectangle_2">
                                        <div className="signup-1-1-0-0-0-1-0-0-0">
                                            <input type="text" placeholder="Kullanıcı Adı" value={this.props.username} onChange={this.props.onUC} className="signup-text_input_2" /> 
                                        </div>
                                    </div>
                                </div>
                                <div className="signup-1-1-0-0-0-1-1">
                                    <div className="signup-line-4" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="signup-1-1-1">
                    <div className="signup-rectangle_3-0">
                        <div className="signup-1-1-1-0-0">
                            <div className="signup-1-1-1-0-0-0">
                                <div className="signup-1-1-1-0-0-0-0">
                                    <div className="signup-email_-0">{"Email:"}</div>
                                </div>
                            </div>
                            <div className="signup-1-1-1-0-0-1">
                                <div className="signup-1-1-1-0-0-1-0">
                                    <div className="signup-rectangle_2-2">
                                        <div className="signup-1-1-1-0-0-1-0-0-0">
                                            <input type="text" placeholder="Email" value={this.props.email} onChange={this.props.onEC} className="signup-text_input-0" /> 
                                        </div>
                                    </div>
                                </div>
                                <div className="signup-1-1-1-0-0-1-1">
                                    <div className="signup-line-5" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="signup-1-1-2">
                    <div className="signup-rectangle_5">
                        <div className="signup-1-1-2-0-0">
                            <div className="signup-_ifre_-0">{"Şifre:"}</div>
                            <div className="signup-1-1-2-0-0-1">
                                <div className="signup-1-1-2-0-0-1-0">
                                    <div className="signup-rectangle_4">
                                        <div className="signup-1-1-2-0-0-1-0-0-0">
                                            <input type="password" placeholder="Şifre" value={this.props.pass} onChange={this.props.onPC} className="signup-text_input-00" /> 
                                        </div>
                                    </div>
                                </div>
                                <div className="signup-1-1-2-0-0-1-1">
                                    <div className="signup-line-8" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="signup-1-1-3">
                    <div className="signup-rectangle_5-4">
                        <div className="signup-1-1-3-0-0">
                            <div className="signup-1-1-3-0-0-0">
                                <div className="signup-1-1-3-0-0-0-0">
                                    <div className="signup-_ifre_-3">{"Şifre Tekrar:"}</div>
                                </div>
                            </div>
                            <div className="signup-1-1-3-0-0-1">
                                <div className="signup-1-1-3-0-0-1-0">
                                    <div className="signup-rectangle_4-3">
                                        <div className="signup-1-1-3-0-0-1-0-0-0">
                                            <input type="password" placeholder="Şifre" value={this.props.passagain} onChange={this.props.onPAC} className="signup-text_input-1" /> 
                                        </div>
                                    </div>
                                </div>
                                <div className="signup-1-1-3-0-0-1-1">
                                    <div className="signup-line-59" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="signup-1-1-4">
                    <div onClick={()=>this.props.history.push('/giris')} className="signup-giri_yap_n-0">
                        {"Giriş yapın"}
                    </div>
                    <div className="signup-1-1-4-1" /> 
                </div>
            </div>
            <div className="signup-1-2" /> 
        </div>
        <div className="signup-2">
            <div onClick={this.props.signup} className="signup-rectangle-0">
                <div className="signup-2-0-0">
                    <div className="signup-kay_t_olun-00">{"Kayıt olun"}</div>
                </div>
            </div>
        </div>
        <div className="signup-3" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}