// Generated by https://pagedraw.io/pages/9839
import React from 'react';
import './state_2.css';

function render() {
    return <div className="state_2-state_2">
        <div className="state_2-0">
            <div className="state_2-rectangle-5" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}