// Generated by https://pagedraw.io/pages/9839
import React from 'react';
import './state_1.css';

function render() {
    return <div className="state_1-state_1">
        <div className="state_1-0">
            <div className="state_1-rectangle-6" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}