// Generated by https://pagedraw.io/pages/9839
import React from 'react';
import './state_3.css';

function render() {
    return <div className="state_3-state_3">
        <div className="state_3-0">
            <div className="state_3-rectangle-6" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}