// Generated by https://pagedraw.io/pages/9957
import React from 'react';
import './studypage.css';

function render() {
    return <div className="studypage-studypage-0">
        <div className="studypage-0">
            <div className="studypage-0-0" /> 
            <div className="studypage-rectangle_2">
                <div className="studypage-0-1-0">
                    <div className="studypage-_renilecek-0">
                        {"Öğrenilecek"}
                    </div>
                </div>
                <div className="studypage-0-1-1">
                    <div onClick={this.props.learnClick} className="studypage-rectangle-0">
                        <div className="studypage-0-1-1-0-0">
                            <div className="studypage-10">{ this.props.learn }</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="studypage-rectangle_3">
                <div className="studypage-0-2-0">
                    <div className="studypage-_al_lacak-0">
                        {"Çalışılacak"}
                    </div>
                </div>
                <div className="studypage-0-2-1">
                    <div onClick={this.props.reviewClick} className="studypage-rectangle-00">
                        <div className="studypage-0-2-1-0-0">
                            <div className="studypage-10-0">{ this.props.review }</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="studypage-0-3" /> 
        </div>
        <div className="studypage-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}