// Generated by https://pagedraw.io/pages/9870
import React from 'react';
import './tfbutton.css';

function render() {
    return <div className="tfbutton">
        { (this.props.state === "wrong") ?
            <div className="tfbutton-wrong-3">
                <div className="tfbutton-0-0-0">
                    <div className="tfbutton-rectangle_2">
                        <div className="tfbutton-0-0-0-0-0">
                            <div className="tfbutton-0-0-0-0-0-0" /> 
                            <div className="tfbutton-do_ru-6">{ this.props.text }</div>
                            <div className="tfbutton-0-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state === "correct") ?
            <div className="tfbutton-correct-7">
                <div className="tfbutton-1-0-0">
                    <div className="tfbutton-rectangle_2-7">
                        <div className="tfbutton-1-0-0-0-0">
                            <div className="tfbutton-1-0-0-0-0-0" /> 
                            <div className="tfbutton-do_ru-5">{ this.props.text }</div>
                            <div className="tfbutton-1-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state === "default") ?
            <div className="tfbutton-default-9">
                <div className="tfbutton-2-0-0">
                    <div className="tfbutton-rectangle_2-0">
                        <div className="tfbutton-2-0-0-0-0">
                            <div className="tfbutton-2-0-0-0-0-0" /> 
                            <div className="tfbutton-do_ru-9">{ this.props.text }</div>
                            <div className="tfbutton-2-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}